sudo: false

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=/opt/ghc/7.10.2/bin:$PATH
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - git clone -b stack http://github.com/diagrams/diagrams-travis travis
  - ./travis/scripts/git_deps.sh
  - stack install gtk2hs-buildtools

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
    - libgmp-dev
    - libgtk-3-dev
    - libcairo2-dev
    - libpango1.0-dev

env:
  global:
    - HEAD_DEPS="diagrams-core diagrams-lib diagrams-cairo diagrams-svg diagrams-postscript diagrams-rasterific diagrams-pgf active dual-tree monoid-extras statestack diagrams-solve"
    - STACK_YAML='travis-stack.yaml'

install:
  - ./travis_long stack --no-terminal --skip-ghc-check setup
  - ./travis_long stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  
notifications:
  email: false
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-builder\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
